ALTER TABLE personel ADD COLUMN IF NOT EXISTS email VARCHAR(100);
ALTER TABLE personel ADD COLUMN IF NOT EXISTS saglik_raporu_tarihi DATE;
ALTER TABLE personel ADD COLUMN IF NOT EXISTS isg_egitim_tarihi DATE;
