-- Add Muvafakatlı to myk_egitim_listesi
INSERT INTO myk_egitim_listesi (ad) 
SELECT 'Muvafakatlı'
WHERE NOT EXISTS (SELECT 1 FROM myk_egitim_listesi WHERE ad = 'Muvafakatlı');

-- Add all official MYK zorunlu meslekler
INSERT INTO myk_egitim_listesi (ad)
SELECT ad FROM (VALUES
  ('Ağır Vasıta Tecrübe Sürücüsü'),
  ('Ahşap Kalıpçı'),
  ('Ahşap Mobilya İmalatçısı'),
  ('Alçı Levha Uygulayıcısı'),
  ('Alçı Sıva Uygulayıcısı'),
  ('Alüminyum Kaynakçısı'),
  ('Armürlü Dokuma Kumaş Desen Hazırlama Elemanı'),
  ('Armürlü Dokuma Kumaş Desinatörü'),
  ('Asansör Bakım ve Onarımcısı'),
  ('Asansör Montajcısı'),
  ('Atık Ayırma İşçisi'),
  ('Atık Koordinatörü'),
  ('Ayakçı (Deri/Kürk Hazır Giyim)'),
  ('Ayakkabı İmalatçısı'),
  ('Baca Kontrol Personeli (Bacacı)'),
  ('Baca Montaj Personeli (Bacacı)'),
  ('Baca Yağlı Kanal Temizleme Personeli'),
  ('Batarya Elektrikli Araç Bakım Onarımcısı'),
  ('Beton Pompa Operatörü'),
  ('Betonarme Demircisi'),
  ('Betoncu'),
  ('Bireysel ve Ticari Klima Sistemleri Montaj ve Servis Elemanı'),
  ('Bireysel ve Ticari Klima Sistemleri Montajcısı'),
  ('Bitim İşlemleri Operatörü'),
  ('Bitkisel Yağ Üretim Operatörü'),
  ('Biyogaz Sistemleri Personeli'),
  ('Boyama Operatörü'),
  ('Buhar Kazanı Operatörü'),
  ('Cam Kesim Elemanı'),
  ('CNC Programcısı'),
  ('CNC Takım Tezgahları Mekanik Servis Görevlisi'),
  ('CNC Takım Tezgahları Uygulama ve Servis Görevlisi'),
  ('Çelik Kaynakçısı'),
  ('Çimento Üretim Elemanı'),
  ('Deri İşlenti Operatörü'),
  ('Direnç Kaynak Ayarcısı'),
  ('Doğal Gaz Altyapı Yapım Kontrol Personeli'),
  ('Doğal Gaz Çelik Boru Kaynakçısı'),
  ('Doğal Gaz Isıtma ve Gaz Yakıcı Cihaz Servis Personeli'),
  ('Doğal Gaz İşletme Bakım Operatörü'),
  ('Doğal Gaz Polietilen Boru Kaynakçısı'),
  ('Doğalgaz Sayaç Sökme Takma Elemanı'),
  ('Dökümcü'),
  ('Duvarcı'),
  ('Ekskavatör Operatörü'),
  ('Elektrik Dağıtım Şebekesi Hat Bakım Görevlisi'),
  ('Elektrik Dağıtım Şebekesi İşletme Bakım Görevlisi'),
  ('Elektrik Dağıtım Şebekesi Kayıp-Kaçak ve Ölçü Kontrol Görevlisi'),
  ('Elektrik Dağıtım Şebekesi Test Görevlisi'),
  ('Elektrik Dağıtımı Scada Operatörü'),
  ('Elektrik Pano Montajcısı'),
  ('Elektrik Sayacı Sökme/Takma Elemanı'),
  ('Elektrik Tesisatçısı'),
  ('Elektrikli Araç Montaj Elemanı'),
  ('Elektro-Mekanik Montaj İşçisi'),
  ('Elektronik ve Elektrikli Ürünler Servisçisi'),
  ('Endüstriyel Boru Montajcısı'),
  ('Endüstriyel Cam Isıl İşlem Elemanı'),
  ('Endüstriyel Cam İşleme Elemanı'),
  ('Endüstriyel Cam Kesim Elemanı'),
  ('Endüstriyel Taşımacı'),
  ('Endüstriyel Yalıtım Camı Üretim Elemanı'),
  ('Florlu Sera Gazlı Cihazlar Teknik Personeli'),
  ('Fotovoltaik Güç Sistemleri Personeli'),
  ('Frezeci'),
  ('Görüntü ve Ses Sistemleri Elemanı'),
  ('Güneş-Isıl Sistem Personeli'),
  ('Güzellik Uzmanı'),
  ('Haddeci'),
  ('Hibrit Araç Bakım Onarımcısı'),
  ('Hidrolik-Pnömatikçi'),
  ('Isı Yalıtımcısı'),
  ('Isıtma Tesisat Bakım Onarım ve Servis Elemanı'),
  ('Isıtma ve Doğal Gaz İç Tesisat Yapım Personeli'),
  ('İnşaat Boyacısı'),
  ('İnşaat İşçisi'),
  ('İplik Bitim İşleri Operatörü'),
  ('İplik Eğirme Operatörü'),
  ('İplik Operatörü'),
  ('İş Makinesi Bakım ve Onarımcısı'),
  ('İşaretçi'),
  ('İskele Kurulum Elemanı'),
  ('İşletme Elektrik Bakımcısı'),
  ('İzabeci'),
  ('Jakarlı Dokuma Kumaş Desen Hazırlama Elemanı'),
  ('Jakarlı Dokuma Kumaş Desinatörü'),
  ('Kartonpiyer Uygulayıcısı'),
  ('Kaynak Operatörü'),
  ('Kent İçi Raylı Sistemler Katener Bakım Elemanı'),
  ('Kesimci (Ayakkabı)'),
  ('Kesimci (Deri/Kürk Hazır Giyim)'),
  ('Kesimci (Saraciye)'),
  ('Kızgın Yağ Kazanı Operatörü'),
  ('Kırma Eleme Tesis Operatörü'),
  ('Köprülü Vinç Operatörü'),
  ('Kuaför'),
  ('Liman Forklift Operatörü'),
  ('Liman Kuru Yük Operasyon Elemanı (Puantör)'),
  ('Liman Operasyon Planlamacısı'),
  ('Liman Pompa ve Tank Saha Operatörü'),
  ('Liman RTG Operatörü'),
  ('Liman Saha İstif Makineleri Operatörü (CRS ve ECS)'),
  ('Liman SSG Operatörü'),
  ('Liman Vinç Operatörü (RTG ve SSG)'),
  ('Maçacı'),
  ('Makine Bakımcı'),
  ('Makine Montajcısı'),
  ('Matkap Tezgah İşçisi'),
  ('Mekanizasyon İşçisi (Maden)'),
  ('Mekanize Kazı Operatörü'),
  ('Mermer-Doğaltaş İmalat Elemanı'),
  ('Mermer-Doğaltaş Ocakçısı'),
  ('Mermer-Doğaltaş Özel İmalat Elemanı'),
  ('Metal Kesim Operatörü'),
  ('Metal Kesimci'),
  ('Metal Levha İşleme Tezgâh İşçisi'),
  ('Metal Levha İşleme Tezgâh Operatörü'),
  ('Metal Sac İşlemeci'),
  ('Mobil Vinç Operatörü'),
  ('Mobil Vinç Operatörü (MHC, Sahil ve Gemi Vinci)'),
  ('Mobilya Döşemecisi'),
  ('Model Makineci (Deri/Kürk Hazır Giyim)'),
  ('Motor Testçisi'),
  ('Motosiklet Bakım Onarımcısı'),
  ('NC/CNC Takım Tezgâhları Elektrik/Elektronik Servis Görevlisi'),
  ('NC/CNC Tezgâh İşçisi'),
  ('Nezaretçi (Maden)'),
  ('Otomasyon Sistemleri Montajcısı'),
  ('Otomasyon Sistemleri Programcısı'),
  ('Otomotiv Boya Onarımcısı'),
  ('Otomotiv Boyacısı'),
  ('Otomotiv Elektrikçisi'),
  ('Otomotiv Elektromekanikçisi'),
  ('Otomotiv Gövde Onarımcısı'),
  ('Otomotiv Kaportacısı'),
  ('Otomotiv Kontrol, Test ve Ayar İşçisi'),
  ('Otomotiv Mekanikçisi'),
  ('Otomotiv Montajcısı'),
  ('Otomotiv Ön Düzencisi'),
  ('Otomotiv Prototipçisi'),
  ('Otomotiv Sac Şekillendirmecisi'),
  ('Otomotiv Sac ve Gövde Kaynakçısı'),
  ('Ön İplik Operatörü'),
  ('Ön Terbiye Operatörü'),
  ('Orman Üretim İşçisi'),
  ('Orman Yetiştirme ve Bakım İşçisi'),
  ('Panel Kalıpçı'),
  ('Plastik Enjeksiyon Üretim Elemanı'),
  ('Plastik Kaynakçısı'),
  ('Plastik Profil Üretim Operatörü (Ekstrüzyon)'),
  ('Plastik Şişirme Film Üretim Operatörü (Ekstrüzyon)'),
  ('Pres İşçisi (Maden)'),
  ('Presçi'),
  ('PVC Doğrama Montajcısı'),
  ('Raylı Sistem Araçları Elektrik Bakım ve Onarımcısı'),
  ('Raylı Sistem Araçları Elektronik Bakım ve Onarımcısı'),
  ('Raylı Sistem Araçları Mekanik Bakım ve Onarımcısı'),
  ('Raylı Sistemler Sinyalizasyon Bakım ve Onarımcısı'),
  ('Refrakterci'),
  ('Röle Görevlisi'),
  ('Rüzgar Güç Sistemi Personeli'),
  ('Sağlık Kuruluşları Kaynaklı Tehlikeli Atık Toplayıcısı'),
  ('Sağlık Kuruluşları Kaynaklı Tıbbi Atık Toplayıcısı'),
  ('Saraciye İmalatçısı'),
  ('Sayacı'),
  ('Sebze ve Meyve Konservesi Üretim Operatörü'),
  ('Seramik Karo Kaplamacısı'),
  ('Ses Yalıtımcısı'),
  ('Sıcak Su Kazanı Operatörü'),
  ('Sıhhi Tesisat Bakım Onarım ve Servis Elemanı'),
  ('Sıvacı'),
  ('Sos Üretim Operatörü'),
  ('Su Yalıtımcısı'),
  ('Tahlisiyeci (Maden)'),
  ('Tarihi Eser Koruma ve Restorasyon Elemanı'),
  ('Taşlama Tezgâh İşçisi'),
  ('Tehlikeli Atık Toplayıcısı'),
  ('Tehlikeli Madde Taşımacılığı Şoförü'),
  ('Tel Makineleri Operatörü'),
  ('Terminal Çekici Operatörü'),
  ('Tornacı'),
  ('Tren Makinisti'),
  ('Tünel Kalıpçı'),
  ('Yangın Yalıtımcısı'),
  ('Yeraltı Hazırlık İşçisi'),
  ('Yüksek Gerilim Kablo Aksesuarları Montajcısı'),
  ('Yüksek Gerilim Teçhizatı Test Elemanı'),
  ('Zeytinyağı Üretim Operatörü')
) AS t(ad)
WHERE NOT EXISTS (SELECT 1 FROM myk_egitim_listesi WHERE myk_egitim_listesi.ad = t.ad);
